### ISSUE TITLE
初步使用 反馈

### ISSUE THREAD

**Issue by chendongbupt** [wuchangming/spy-debugger#1]
环境： win7 + Android
能正常使用， 微信-- QQ浏览器 切换使用， 有些 报错 日志：
WiInspectorImpl.hideDOMNodeHighlight()  : TypeError :   'off'  undefined
Object().childNodeInserted() : TypeError :  '_insertChild'  undefined

欠缺功能： 
1： 不能看 css js 源文件 (微信的weinre工具修改源文件会断开)
2：console --  jQuery  document.querySelector() 查找DOM， 不能返回DOM结构

**Comment by wuchangming** [comment]
研究下看看微信怎么实现的

**Comment by dannyliou** [comment]
这个问题确实有
```
Object().childNodeInserted() : TypeError : '_insertChild' undefined
```

欠缺功能还有：
> js错误没有捕获并在console中显示出来，看不出js错误

**Comment by wuchangming** [comment]
@dannyliou 
`Object().childNodeInserted() : TypeError : '_insertChild' undefined`
这个应该是weinre的bug，估计比较难修复了

这个问题：
>js错误没有捕获并在console中显示出来，看不出js错误

**你试试打开页面前就打开Console的tab。js错误应该是会打印出来的。**

![1 pic](https://cloud.githubusercontent.com/assets/5039340/17044516/36be6a52-4ff3-11e6-80d3-09ec9521cd24.jpg)

**Comment by wuchangming** [comment]
@chendongbupt 
最新版本3.X.X已添加查看css js 源文件的功能。
