### ISSUE TITLE
[nodejs V7版本崩溃问题]我输入spy-debugger进入某一个页面就报错。然后自动退出当前spy-debugger的执行命令。

### ISSUE THREAD

**Issue by wuxiaolan91** [wuchangming/spy-debugger#10]
λ spy-debugger
(node:17776) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
正在启动代理
2016-11-03T09:48:35.681Z index.js: starting server at http://localhost:51610
node-mitmproxy启动端口: 9888
浏览器打开 ---> http://127.0.0.1:51615
2016-11-03T09:48:49.156Z index.js: target t-2: weinre: target t-2 connected to client c-1
2016-11-03T09:48:51.130Z index.js: target t-3: weinre: target t-3 connected to client c-1
2016-11-03T09:48:51.192Z index.js: target t-2: weinre: target t-2 disconnected from client c-1
D:\Program Files\nodejs\node_modules\.spy-debugger_npminstall\node_modules\.3.10.2@anyproxy\proxy.js:208
                    logUtil.printLog('Caught exception: ' + (err.stack || err), logUtil.T_ERR);
                                                                ^

TypeError: Cannot read property 'displayName' of undefined

**Comment by wuchangming** [comment]
你的node.js 和spy-debugger版本分别是多少呢 ，执行命令：`node --version` 和 `spy-debugger --version` 看看。

**Comment by evanyangg** [comment]
@wuchangming 
$ node --version
v7.1.0
$ spy-debugger --version
3.2.2
我也出现了这个问题,已经重新安装过,在某个页面还是会有这个问题

**Comment by wuchangming** [comment]
@evanyangg ,抽空改下启动weinre的方式。谢谢反馈问题

**Comment by evanyangg** [comment]
@wuchangming 我试用了一下github里面的weinre项目 也会出现同样的问题

**Comment by wuchangming** [comment]
可能是weinre不兼容最新版的nodejs

**Comment by evanyangg** [comment]
@wuchangming 我从原来的7.1改成6.9.1
自动退出的问题没有了.现在可以自动调试了.
![image](https://cloud.githubusercontent.com/assets/22952321/20737308/cc89d1d4-b6e6-11e6-8cd1-d2637336466c.png)
但是这个属性displayName依然是undefined

**Comment by wuchangming** [comment]
确实是nodejs7以上的版本有问题。我这边看看怎么能修复

**Comment by wuchangming** [comment]
![image](https://cloud.githubusercontent.com/assets/5039340/20739430/744b9dcc-b6f5-11e6-92c0-3e73189dfaca.png)

nodejs 7.0以上版本导致spy-debugger崩溃的bug

### 已在`3.2.3`版本修复

**Comment by evanyangg** [comment]
@wuchangming  辛苦辛苦

**Comment by maicong** [comment]
还是会退出

```
➜  ~/Web  spy-debugger
正在启动代理
2016-12-28T07:59:16.116Z spy-debugger: starting server at http://localhost:50377
(node:57694) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
本机在当前网络下的IP地址为：10.0.4.67
node-mitmproxy启动端口: 9888
浏览器打开 ---> http://127.0.0.1:50382
(node:57694) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:57694) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
/Users/singsen/.config/yarn/global/node_modules/weinre/lib/utils.js:183
    funcName = func.displayName || func.name || callSite.getFunctionName();
                   ^

TypeError: Cannot read property 'displayName' of undefined
(node:57694) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
➜  ~/Web
```

**Comment by wuchangming** [comment]
用yarn安装确实还会用问题。
在想办法看怎样能修复

**Comment by wuchangming** [comment]
@maicong ，用yarn安装，node为v7依然出现退出的问题已在3.4.0版本修复
