### ISSUE TITLE
error: getaddrinfo RNOTFOUND null null:80

### ISSUE THREAD

**Issue by jintangWang** [wuchangming/spy-debugger#105]
![image](https://user-images.githubusercontent.com/12557847/43376227-225876d6-93ec-11e8-8327-72d3037d8d0e.png)
前四步都完成了，手机就是无法访问pc在hosts文件中配置的域名，当我访问 pc的Ip:9888 的时候就报上面的那个错，请问怎么解决？

**Comment by jintangWang** [comment]
对了，我的 spy-debugger 版本：
![image](https://user-images.githubusercontent.com/12557847/43376329-b35a5776-93ec-11e8-8694-012c1f3f6d86.png)

**Comment by PatWu16** [comment]
@jintangWang 请问解决了吗？我也遇到同样的问题

**Comment by jintangWang** [comment]
@PatWu16 连接同一个网络，设置手动代理，我用了360随身wifi不行，电脑连手机热点也不可以

**Comment by jintangWang** [comment]
close
