### ISSUE TITLE
spy-debugger -p  xxx 设置端口不成功啊

### ISSUE THREAD

**Issue by skyweaver213** [wuchangming/spy-debugger#115]
<img width="560" alt="debugger 2x" src="https://user-images.githubusercontent.com/5363176/50443443-72ca6580-093e-11e9-91ca-30045f20455f.png">

如截图， 不加端口能正常启动，加了端口 无论字符串还是int 都是失败的。

**Comment by wuchangming** [comment]
@skyweaver213 ,感谢反馈。

请问spy-debugger、npm、node的版本分别是？电脑的系统是？
**查看命令：**
```
spy-debugger --version
npm --version
node --version
```

**Comment by skyweaver213** [comment]
> @skyweaver213 ,感谢反馈。
> 
> 请问spy-debugger、npm、node的版本分别是？电脑的系统是？
> **查看命令：**
> 
> ```
> spy-debugger --version
> npm --version
> node --version
> ```
mac os 10.14
<img width="410" alt="wx20190104-100349 2x" src="https://user-images.githubusercontent.com/5363176/50670662-1cc58400-1008-11e9-8060-ccd1af147591.png">

**Comment by wuchangming** [comment]
@skyweaver213 ,应该是5389 这个端口被占用了。你换个端口试试？
报错提示不太友好。

**Comment by skyweaver213** [comment]
@wuchangming 嗯嗯 重新试了一下， 可以了，谢谢拉。

**Comment by wuchangming** [comment]
问题先关闭了。
占用端口的错误提示后面我优化下
