### ISSUE TITLE
可以调试安卓端内的字符串html吗，不是src引入的那种？

### ISSUE THREAD

**Issue by llqi** [wuchangming/spy-debugger#117]

**Comment by llqi** [comment]
现在可以调试端内src的h5，但是html字符串无效

**Comment by wuchangming** [comment]
只能调试webview或者浏览器通过网络请求打开的页面。
这里指的html字符串指的是在app本地文件？

**Comment by llqi** [comment]
@wuchangming 
是一个webview引入的包内的html文件 不是src引入的
我这里测试src引入的webview可以调试  包内文件引入的html webview不行

**Comment by wuchangming** [comment]
@llqi, 是的，这种请求确实不支持调试。

**Comment by llqi** [comment]
@wuchangming ok 🙏
