### ISSUE TITLE
请问下作者，这个工具和 whistle 有什么区别？

### ISSUE THREAD

**Issue by DMQ** [wuchangming/spy-debugger#127]

**Comment by wuchangming** [comment]
@DMQ ，原理大同小异吧，whistle 可以自定义的比较多，spy-debugger 不需要开发看太多说明，拿来就用。

**Comment by DMQ** [comment]
> @DMQ ，原理大同小异吧，whistle 可以自定义的比较多，spy-debugger 不需要开发看太多说明，拿来就用。

好的！😁
