### ISSUE TITLE
访问线上无法抓包，只有加了host才可以，不知道为什么

### ISSUE THREAD

**Issue by horsesuper** [wuchangming/spy-debugger#13]
必须有host，且在host 内的域名才能抓到，其他的都不行

**Comment by wuchangming** [comment]
你本机的浏览器不配置host能不能访问线上呢？

**Comment by horsesuper** [comment]
可以的，浏览器没有问题，手机挂代理后必须加上
 127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
才可以正常

**Comment by wuchangming** [comment]
这个问题我研究下。
后面找时间优化下，把内部指向localhost的域名都改成127.0.0.1

**Comment by horsesuper** [comment]
(b~_^)b ,东西做的真不错，我推荐给好几个人用了，有个小建议，目前 启动服务后 显示的是：
```
node-mitmproxy启动端口: 9888
浏览器打开 ---> http://127.0.0.1:62226
```

常常是不知道自己的ip 的，还需要在电脑里找一下。能不能 控制台输出的时候把本机ip 也一起打印上，这样比较一目了然。

**Comment by wuchangming** [comment]
嗯嗯，谢谢你的建议。
现在有计划过年的时候找时间重构一下。

你这个建议不错，我会加上的。感谢！  ：）

**Comment by wuchangming** [comment]
@horsesuper  ,ip提示已在**3.2.2**版本加上
  
![image](https://cloud.githubusercontent.com/assets/5039340/21475936/4662177e-cb6d-11e6-865e-502ee142d50e.png)

**Comment by horsesuper** [comment]
太棒了

**Comment by wuchangming** [comment]
@horsesuper 
host的问题已经在**3.5.1版本**修复
