### ISSUE TITLE
是否支持axios发起请求?

### ISSUE THREAD

**Issue by evanyangg** [wuchangming/spy-debugger#14]
刚开始看到这个调试神器,一下子激动了一把,按照步骤一切正常,但是我的前端页面用是用axios发起的http请求,感觉所有的请求是发生了错误
![image](https://cloud.githubusercontent.com/assets/22952321/20662650/49a0d554-b58f-11e6-8fca-0bd63af605dc.png)
这个是请求拦截的log,请大神过目!

**Comment by evanyangg** [comment]
![image](https://cloud.githubusercontent.com/assets/22952321/20662703/9287e56e-b58f-11e6-8aaf-7bdfc6504877.png)
同时,命令行还伴随这个错误日志

**Comment by wuchangming** [comment]
![](https://cloud.githubusercontent.com/assets/22952321/20662703/9287e56e-b58f-11e6-8aaf-7bdfc6504877.png)
这个报错应该和请求无关，这个是weinre解析页面dom的报错。

你所指的axios发起的http请求的错误，我没看太懂。。
![](https://cloud.githubusercontent.com/assets/22952321/20662650/49a0d554-b58f-11e6-8fca-0bd63af605dc.png)
这个图是你服务后台拦截到的？

另外你看看anyproxy抓包的内容看能看出什么不异常没？
或者你提供下你的网页地址我看看。

**Comment by evanyangg** [comment]
@wuchangming 
![](https://cloud.githubusercontent.com/assets/22952321/20662650/49a0d554-b58f-11e6-8fca-0bd63af605dc.png)
这个图是前端请求的时拦截的log.
还有前台使用的vuejs,使用的是虚拟dom,如果您现在在线的话 可以通过sun.s3.natapp.cc 可以访问我的主页

**Comment by wuchangming** [comment]
看了下app.js 的文件太大了7M多，其他我没看出什么问题。你可以优化下这个js。
axios是支持的。

**Comment by evanyangg** [comment]
@wuchangming 这个是开发模式,引入的库比较多,所以占用的空间比较大,如果build的话就成单个html页面了,js也会按需打包就小了

**Comment by evanyangg** [comment]
![image](https://cloud.githubusercontent.com/assets/22952321/20703022/0a7818f8-b655-11e6-869f-ae9e30f2074a.png)
您好,又来打扰了 ,我发现我的请求好像没有发出去,我用charles 没有看到任何关于代码中的请求,
上面是请求的状态,不知道哪里出了问题

**Comment by wuchangming** [comment]
你是用了spy-debugger+charles?

**Comment by wuchangming** [comment]
你电脑的网络有没问题呢？

我这边看了都挺正常的
<img width="709" alt="screen shot 2016-11-29 at 5 12 49 pm" src="https://cloud.githubusercontent.com/assets/5039340/20703604/485717da-b657-11e6-8d00-655813fe54f4.png">

**Comment by evanyangg** [comment]
@wuchangming 非常感谢,我已经用起来了.很强大👍
![image](https://cloud.githubusercontent.com/assets/22952321/20703776/04d31134-b658-11e6-9238-8aa33b64ebbb.png)
但是我遇到了一个这个问题,在有的页面是正常调试的,但是跳转到我的某一个页面 会出现这个问题,然后调试会自动断开.

**Comment by evanyangg** [comment]
已经可以使用了 @wuchangming 非常感谢
