### ISSUE TITLE
不显示外联的CSS样式

### ISSUE THREAD

**Issue by MrLeo** [wuchangming/spy-debugger#16]
在使用weinre调试样式的时候，外联css文件中的样式没有在右侧显示出来，能帮忙看下什么问题吗

![image](https://cloud.githubusercontent.com/assets/3761566/20878222/ab8646a4-bb08-11e6-9f75-210a175086aa.png)

**Comment by wuchangming** [comment]
由于weinre只是通过js去读取了该元素计算过后所拥有的css属性。并不能像直接调试浏览器样式那样把所有的class包涵的css属性列出来。

所以你只能看到各种css样式叠加之后运算的最终结果。
