### ISSUE TITLE
iOS14功能失效

### ISSUE THREAD

**Issue by tanxingeng** [wuchangming/spy-debugger#163]
手机升级到iOS14后，功能实效。
刚好手上有多台iPhone，测试过，10-12的版本，每次都可以，13的版本，偶尔就截不到。
对iOS14版本，进行更详细的测试，使用Safari浏览器访问链接，就没有截获到，使用Chrome访问同一链接，就可以被截获到，因此微信访问，调用Safari，或者说，与Safari一样调用了iOS14的内核某部分，导致微信访问就截获不到了。

**Comment by tanxingeng** [comment]
补充，访问的地址，有调用微信API的https链接。

**Comment by realwnc** [comment]
我也是一样，只要是ios14或android7版本及以上的safari都不能截获任何网站(https)!

**Comment by wuchangming** [comment]
3.8.6 版本已修复该bug
