### ISSUE TITLE
我又来了,在适用自定义请求头时,请求头信息为null?

### ISSUE THREAD

**Issue by evanyangg** [wuchangming/spy-debugger#17]
一下午的时间都在找这个问题,开始以为是axios的问题,后来从代理ip环境切换的真实环境中,请求头信息可以带到后台,就是使用代理的时候请求头信息带不过去.

**Comment by wuchangming** [comment]
你是怎么定义请求头？加了什么请求头字段，我明天试试

**Comment by evanyangg** [comment]
@wuchangming
![3547c6a3-834b-4a11-b73b-6ab802bdd30d](https://cloud.githubusercontent.com/assets/22952321/20883741/aa84ec50-bb22-11e6-8a1a-cae4f97fd803.png)

![180a5cd0-d536-4162-b26f-416c1f254054](https://cloud.githubusercontent.com/assets/22952321/20883755/bd453f5c-bb22-11e6-963a-933b11da0b29.png)
截图发给你了 ,你明天试试看. 就是那个authorization_token

**Comment by wuchangming** [comment]
@evanyangg ，还没调试，但估计是因为key包含了下划线。搜了下建议不要用下划线，好像nginx也有类似问题

**Comment by evanyangg** [comment]
@wuchangming
确实是这个问题,谢谢!
