### ISSUE TITLE
苹果手机浏览器无法安装证书

### ISSUE THREAD

**Issue by zhangtao3** [wuchangming/spy-debugger#19]
用的的iphone6 plus，UC浏览器扫证书地址二维码，UC浏览器显示无法打开文件。同样操作步骤，安卓手机是正常的

**Comment by wuchangming** [comment]
用Safari试试

**Comment by bowen31337** [comment]
我用的是iphone7，safari打开不了cert页面，proxy设置和不设置都一样。

**Comment by wuchangming** [comment]
@bowen31337 ，
确认下下面几项：
1、spy-debugger 是否正常启动
2、电脑和手机需要保持在同一网络下。
3、手机是否开了翻墙vpn？开了需要关掉

**Comment by bowen31337** [comment]
@wuchangming
我已经确认安装正常，同一wifi，手机没有VPN。怎么解？

**Comment by wuchangming** [comment]
@bowen31337
切换到 “请求抓包”界面，点击：
![image](https://cloud.githubusercontent.com/assets/5039340/21952615/0efdd09e-da5d-11e6-8bfc-c967545df240.png)

能否下载证书？

**Comment by bowen31337** [comment]
@wuchangming,  可以下载，但是下载到我的mac里面，用手机无法下载啊

**Comment by wuchangming** [comment]
1、如果点按钮可以下载说明证书时已经正确生成了。
2、配置代理后，你访问下https的页面。如百度，如果无法访问，说明你设置代理成功了。

这个时候你访问证书下载链接试试。

最新版本试试：3.6.1。
证书下载地址改短了：http://s.xxx

**Comment by bowen31337** [comment]
@wuchangming 设置代理后什么链接都打不开， 试过手机的safari，和chrome，都打不下载链接

**Comment by wuchangming** [comment]
@bowen31337 ，非https的网址能打开不？ 如：http://cn.bing.com/

**Comment by bowen31337** [comment]
@wuchangming  打不开所有的链接，不管是http还是https

**Comment by wuchangming** [comment]
截两个图我看看。
**spy-debugger 启动日志**  
**iphone的代理设置界面**

**Comment by bowen31337** [comment]
@wuchangming  去哪里找启动日志？
我的iphone 7的代理设置是
ip：192.168.1.110（我mac 电脑的IP地址）
port：9888

**Comment by wuchangming** [comment]
![image](https://cloud.githubusercontent.com/assets/5039340/22015174/ee1237a4-dcdb-11e6-8e36-86093b353d4d.png)

**Comment by bowen31337** [comment]
@wuchangming 
![screen shot 2017-01-17 at 8 43 17 pm](https://cloud.githubusercontent.com/assets/3508255/22015321/adcfd7cc-dcf5-11e6-8d4b-d399a85c66a5.png)

**Comment by wuchangming** [comment]
@bowen31337 ，感觉都挺正常的。。。。。

你的mac是怎么连接Wi-Fi的？
会不会和这个问题里说的一样？https://github.com/wuchangming/spy-debugger/issues/21

**Comment by bowen31337** [comment]
@wuchangming 我的mac是wifi连路由器的，下面是ifconfig的配置
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 34:36:3b:7b:27:ca
	inet6 fe80::3636:3bff:fe7b:27ca%en0 prefixlen 64 scopeid 0x4
	inet 192.168.1.110 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active

**Comment by wuchangming** [comment]
没看出任何问题。。。

手机设置完代理后，访问页面时。
spy-debugger 的“抓包请求”页面有记录到日志没？
或者终端有没输出日志？

**Comment by wuchangming** [comment]
iphone 上是否设置的这里？

<img width="200px" src="https://cloud.githubusercontent.com/assets/5039340/22016404/23067984-dce1-11e6-9408-d70917ff658d.png" />

**Comment by bowen31337** [comment]
@wuchangming 对， iphone是在这里设置的

**Comment by wuchangming** [comment]
@bowen31337 

手机设置完代理后，访问页面时。
spy-debugger 的“抓包请求”页面有记录到日志没？
或者终端有没输出日志？

iphone 显示的ip是多少？
![image](https://cloud.githubusercontent.com/assets/5039340/22017548/c4958ae8-dce5-11e6-9e06-1e4433ed6792.png)

**Comment by bowen31337** [comment]
@wuchangming 抓包页面一直处于加载状态，截图：
![screen shot 2017-01-17 at 10 16 10 pm](https://cloud.githubusercontent.com/assets/3508255/22018383/af4f9e22-dd02-11e6-8249-811206285b5b.png)

**Comment by wuchangming** [comment]
@bowen31337 ，实在找不出什么原因了....我用iphone7试了也没发现问题。你试试把mac上的spy-debugger删除后，再重新安装试试看。暂时想不出别的原因了。😢

**Comment by bowen31337** [comment]
@wuchangming 已经重装了好几次，现在是最新的版本，3.6.1。 我mac里面装了virtual box，是不是有可能是virtual box里面有虚拟的网卡造成的？

**Comment by wuchangming** [comment]
@bowen31337 我没装virtual box，但有装VMware。也没什么问题

1、你virtual box的网卡是怎么接入wifi的？是实用mac的共享网络？

2、mac能ping 通手机的ip么？

**Comment by bowen31337** [comment]
@wuchangming 我的router的ip isolation 取消后，抓包就好了， 但是页面调试还是什么都没有，怎么解？

**Comment by bowen31337** [comment]
@wuchangming 现在有眉目了，weinre出现报错信息：
`{ ---------------------------------------------------------
error: Error: socket hang up
---------------------------------------------------------
stack:
   _http_client.js:254 - undefined()
   _http_client.js:286 - undefined()
         events.js:101 - undefined()
         events.js:188 - undefined()
            net.js:498 - undefined() code: 'ECONNRESET' }
(node:10725) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot read public key. OID is not RSA.`

**Comment by wuchangming** [comment]
打开什么页面都不能调试？还是某个URL？https://
baidu.com试试

**Comment by bowen31337** [comment]
@wuchangming  看看下面的
`{ ---------------------------------------------------------
error: Error: socket hang up
---------------------------------------------------------
stack:
   _http_client.js:254 - undefined()
   _http_client.js:286 - undefined()
         events.js:101 - undefined()
         events.js:188 - undefined()
            net.js:498 - undefined() code: 'ECONNRESET' }`

**Comment by wuchangming** [comment]
小程序确实不行。
小程序通信过程应该用的是微信自定义的安全协议mmtls。这个现在没办法通过https证书的方式解密。

**Comment by bowen31337** [comment]
@wuchangming 理论上把weinre的script放到小程序里面，就能页面调试了，对吧

**Comment by wuchangming** [comment]
@bowen31337 ,
weinre应该只能解析html的dom树。
我还没真正看过小程序的具体实现。不知道对微信对小程序webview做了多少改造。

**Comment by bowen31337** [comment]
@wuchangming  如果不能调试小程序的话，用fiddler + weinre也能对手机页面调试，但没有多大意义。 不过，谢谢了，加一个星星。

**Comment by wuchangming** [comment]
@bowen31337 

**THX!**
是的，这个工具只是在不能USB插线调试的时候调试H5页面比较方便。其他情况还是有很多可选的替代方案。

**Comment by jacobcyl** [comment]
> @wuchangming 我的router的ip isolation 取消后，装了crt，抓包就好了，mac也能ping 手机，之前不行。 但是页面调试还是什么都没有，怎么解？

请问你是怎么解决的，我的问题跟你的一样，就是不知道 “我的router的ip isolation 取消后” 这句话的意思，请问具体怎么做？

**Comment by okboy5555** [comment]
同问题

**Comment by dumuchenglin123** [comment]
![image](https://user-images.githubusercontent.com/20918639/50390207-3563ad80-076f-11e9-9808-345def527cd2.png)
为什么我的调试页面显示这样

**Comment by wuchangming** [comment]
@dumuchenglin123 ,单独建了issuse跟踪该问题。
https://github.com/wuchangming/spy-debugger/issues/114
