### ISSUE TITLE
微信开发新手请教

### ISSUE THREAD

**Issue by ivanberry** [wuchangming/spy-debugger#2]
那怎么在微信里打开我的页面呀？要分享给自己微信帐号吗？谢谢

**Comment by wuchangming** [comment]
你的页面有网址没？
你可以在微信对话框里输入网址，然后发送，然后点这个网址。就能打开。

比如随便找个好友输入：www.baidu.com, 然后发送给对方。然后点击链接就行。。。

**Comment by ivanberry** [comment]
@wuchangming 谢谢，问题解决，谢谢
