### ISSUE TITLE
扫码安装不了证书，报错 404 

### ISSUE THREAD

**Issue by baymaxking** [wuchangming/spy-debugger#20]
用手机扫码无法打开网址，报错404，spy-debugger 安装正常已打开，手机和电脑是同一网络，已打开VPN

**Comment by wuchangming** [comment]
参考：https://github.com/wuchangming/spy-debugger/issues/3

**Comment by baymaxking** [comment]
手机要怎么设置代理呢？能说的详细一点嘛，很不好意思……

**Comment by baymaxking** [comment]
我用手机设置代理，还是 404

**Comment by wuchangming** [comment]
安卓参考：https://www.zhihu.com/question/21474174
iOS： http://www.itunes123.com/jc/4465.shtml

**Comment by wuchangming** [comment]
看下spy-debugger 有没正常启动，保证手机和pc在同一个wifi下。

**Comment by baymaxking** [comment]
![default](https://cloud.githubusercontent.com/assets/19190353/21383600/8cd5f6e6-c7a1-11e6-8a9f-613f824e0301.png)
代理也开了， spy-debugger 也启动了  电脑插的网线，手机用的WIFI 是同一网络

**Comment by baymaxking** [comment]
手机可以正常的访问  YouTube

**Comment by baymaxking** [comment]
手机可以正常的访问  YouTube

**Comment by baymaxking** [comment]
手机可以正常的访问  YouTube

**Comment by baymaxking** [comment]
手机可以正常的访问  YouTube

**Comment by wuchangming** [comment]
把你手机的翻墙关掉试试

**Comment by baymaxking** [comment]
我用的魅族手机，用  微信  百度  QQ  UC  和魅族手机自带的浏览器都试过了

**Comment by wuchangming** [comment]
感觉是你的手机代理没设置成功

**Comment by baymaxking** [comment]
手机代理不就是翻墙嘛？把IP地址填到  服务器上……  没有别的办法安装证书了嘛？

**Comment by wuchangming** [comment]
代理不是这个意思，是把你手机的请求代理到你的电脑上。
安卓参考：https://www.zhihu.com/question/21474174

**Comment by baymaxking** [comment]
OK 了  ， 谢谢 ，成功了…… 太不容易了……

**Comment by wuchangming** [comment]
嗯嗯，
看来这个问题可以写成FAQ了。比较多提类似的issue
