### ISSUE TITLE
https域代理在ios上安装了证书依旧无法使用

### ISSUE THREAD

**Issue by choui** [wuchangming/spy-debugger#29]

**Comment by wuchangming** [comment]
什么现象呢？
重启webview试试？

**Comment by iampomelo** [comment]
这个问题已解决，iOS下装完证书后还要在”设置“->”通用“->"关于本机“->”证书信任设置"对证书完全信任。

**Comment by cloudroc** [comment]
问题是证书地址失效啊

**Comment by wuchangming** [comment]
@cloudroc, 需要先把手机请求设置代理到pc才能下载证书，另外手机上的翻墙软件可能会影响安装，需要关闭
