### ISSUE TITLE
http://spydebugger.com/cert 失败

### ISSUE THREAD

**Issue by notech** [wuchangming/spy-debugger#3]
ping spydebugger.com
ping: cannot resolve spydebugger.com: Unknown host

**Comment by wuchangming** [comment]
手机要先设置代理后再安装证书 。

第一次启动spydebugger会生成CA证书，位置在你本机的%HOMEPATH%/node-mitmproxy/node-mitmproxy.ca.crt。证书的安装地址只是代理做了转发。

**Comment by dotview** [comment]
同样的问题，这个地址ping不通了

**Comment by wuchangming** [comment]
@dotview 。是的，这个地址是只有通过`spy-debugger`的代理才能访问到的。是ping不通的。

证书的安装地址只是代理做了转发。

**Comment by dotview** [comment]
谢谢！可以了。

**Comment by notech** [comment]
完美解决

**Comment by pamxy** [comment]
> @dotview 。是的，这个地址是只有通过`spy-debugger`的代理才能访问到的。是ping不通的。
> 
> 证书的安装地址只是代理做了转发。

确实解决了我的问题，谢谢！
