### ISSUE TITLE
请问, xcode 自带的 IOS 模拟器的 WIFI 代理怎么设置?

### ISSUE THREAD

**Issue by wh-Coder** [wuchangming/spy-debugger#48]
找不到网络管理

**Comment by wuchangming** [comment]
@wh-Coder ，模拟器用的应该就是本机mac的网络。启动spy-debugger后把mac的网络请求代理到127.0.0.1:9888上即可。证书在mac下的路径：%HOMEPATH%/node-mitmproxy/node-mitmproxy.ca.crt 直接安装即可。
