### ISSUE TITLE
问一下，我想抓包把本地的文件替换线上的文件能做到吗？

### ISSUE THREAD

**Issue by sunriseshow** [wuchangming/spy-debugger#5]
问一下，我想抓包把本地的文件替换线上的文件能做到吗？

**Comment by wuchangming** [comment]
可以，anyproxy的Map Local功能支持替换文件
![maplocal](https://cloud.githubusercontent.com/assets/5039340/17737344/49450ab0-64bf-11e6-9bef-4098ed1db3c9.jpg)
