### ISSUE TITLE
证书需要密码？

### ISSUE THREAD

**Issue by Fxhhahaha** [wuchangming/spy-debugger#54]
按说明配置，抓包可看到数据，但是下载证书后安装需要密码？

**Comment by wuchangming** [comment]
@Fxhhahaha ，那个密码是你手机的锁屏密码

**Comment by Fxhhahaha** [comment]
原谅我的无知。。。之前没有过类似的安装经历

**Comment by Fxhhahaha** [comment]
@wuchangming 我的安卓手机是图案和指纹，并没有密码。然后我取消了图案解锁，设置了一个密码后，再次安装就不再提示我输入密码了。最后我重新设置回来了，如果以后有小伙伴遇到类似的问题可以参照我的解决方法- -

**Comment by wuchangming** [comment]
@Fxhhahaha ，👍
