### ISSUE TITLE
mac 10.12.6 spy-debugger 无法正常调试

### ISSUE THREAD

**Issue by sujiewen** [wuchangming/spy-debugger#55]
spy-debugger -w true -p 8888 手机设置代理后，我苹果手机访问www.qq.com,safari白屏，进度条一直卡在那里,无法正常显示。
spy-debugger anyproxy都能抓到响应的包，但是spy-debugger页面调试就没有办法显示响应调试页面

spy-debugger 3.6.5

spy-debugger -w true -p 8888 运行后，显示的数据
![2017-08-28 3 20 03](https://user-images.githubusercontent.com/1973318/29764801-3e04f95c-8c0b-11e7-8379-c42e5cc69f0f.png)

spy-debuggerebugger页面调试截图
![2017-08-28 4 12 09](https://user-images.githubusercontent.com/1973318/29764915-b1928722-8c0b-11e7-81a6-b95cb369ea46.png)

spy-debuggerebugger anyproxy页面截图
![2017-08-28 4 12 18](https://user-images.githubusercontent.com/1973318/29764942-cc9c4558-8c0b-11e7-9e10-3bd3f0a6ca60.png)

**Comment by wuchangming** [comment]
@sujiewen ,是否正确安装了证书？iOS安装完后需要打开证书开关，参考：https://github.com/wuchangming/spy-debugger/issues/42

**Comment by sujiewen** [comment]
@wuchangming 证书我安装饿了，你说这个证书还有开关？

**Comment by wuchangming** [comment]
@sujiewen ,未打开开关你抓到的应该都是http的请求，https的无法抓包。

**Comment by sujiewen** [comment]
@wuchangming 我现在把这个证书开关打开，还是不行的

**Comment by wuchangming** [comment]
@sujiewen ,看了下www.qq.com的资源确实有点问题。。我找时间看看。
其他地址应该是可以的如：www.baidu.com。

**Comment by sujiewen** [comment]
@wuchangming 谢谢

**Comment by wuchangming** [comment]
@sujiewen ,该问题在最新的3.6.6版本已修改。更新或者重新安装最新spy-debugger即可。

**Comment by LanceCH** [comment]
华为手机 emui5.0 无法正常调试 问题跟楼上的一毛一样 只能抓包 不能页面调试

**Comment by wuchangming** [comment]
@LanceCH ，spy-debugger什么版本？
命令spy-debugger --version查看版本

**Comment by LanceCH** [comment]
3.6.6今天刚安装的

**Comment by wuchangming** [comment]
@LanceCH ，能否提供下你手机上使用的浏览器类型？还有你想调试访问的网址地址？

**Comment by caiyawen** [comment]
![image](https://user-images.githubusercontent.com/18025400/30478088-1d16a584-9a42-11e7-84e9-9ebe564b13f9.png)

我也遇到了这个问题，我下载的版本是3.6.7，手机是ios10.3.3,本来想调试自己的网站，打不开，然后尝试www.baidu.com,还是打不开。。。求解

**Comment by wuchangming** [comment]
@caiyawen 是否正确安装了证书？iOS安装完后需要打开证书开关，参考：https://github.com/wuchangming/spy-debugger/issues/42

**Comment by caiyawen** [comment]
@wuchangming  安装过了，且手动打开了证书开关。用一台安卓手机测试的时候可以打开网页，但是电脑上还是显示不出来，用苹果手机测试的时候是无法打开网页，电脑上页显示不出来。。

**Comment by wuchangming** [comment]
@caiyawen ，还麻烦提供下一些信息，我定位下问题看看。
nodejs是什么版本？是访问特定的url才有问题？手机访问baidu试试呢？手机使用的是什么浏览器？

**Comment by caiyawen** [comment]
@wuchangming  node 版本为v8.1.0； 访问任意路由都有问题，包括百度；苹果手机使用的safari浏览器，安卓手机使用的uc浏览器。有一步操作不知道是不是有问题，你说不能使用微信浏览器访问安装证书的二维码地址，但是我用的微信去识别的二维码，然后复制地址到safari浏览器去安装的。不过按道理应该没什么问题吧。。

**Comment by caiyawen** [comment]
@wuchangming  后来我又试过用charles设置代理，貌似还是不行。。

**Comment by caiyawen** [comment]
@wuchangming  我电脑上一直打开着shadowsockes,跟这个有没有关系？

**Comment by wuchangming** [comment]
@caiyawen ,倒是有可能。关掉shadowsockes试试？

上面你提到用uc浏览器的问题。uc浏览器比较特殊一点，调试需要使用命令 
```
spy-debugger -b false
```
参考：https://github.com/wuchangming/spy-debugger#是否只拦截浏览器发起的https请求

**Comment by caiyawen** [comment]
@wuchangming 好的，我中午试一下，十分感谢！

**Comment by caiyawen** [comment]
@wuchangming  我在关闭了shadowsockes后执行spy-debugger -b false，然后打开手机端uc浏览器，这时手机端页面可以正常访问了，且AnyProxy显示请求都正常，但是页面调试处仍无法显示，控制台有个warning如下
![image](https://user-images.githubusercontent.com/18025400/30530539-0cc49ee0-9c7a-11e7-9033-3d069503735b.png)

**Comment by wuchangming** [comment]
@caiyawen ，你指的调试是？按道理控制台有显示应该是正常了

**Comment by caiyawen** [comment]
![image](https://user-images.githubusercontent.com/18025400/30530660-2d33e5cc-9c7b-11e7-9133-a982e273da8b.png)

**Comment by wuchangming** [comment]
@caiyawen ，奇怪了。
pc 是mac还是windows？
刷新下spy-debugger的调试页面呢？
再帮忙截图下终端运行的log看看。

**Comment by caiyawen** [comment]
pc是mac air。辛苦辛苦。
![image](https://user-images.githubusercontent.com/18025400/30531126-ae8278d4-9c7e-11e7-9c50-91ab4c57ef58.png)
![image](https://user-images.githubusercontent.com/18025400/30531114-a287912c-9c7e-11e7-9470-be98f92888a2.png)
![image](https://user-images.githubusercontent.com/18025400/30531153-dae0e302-9c7e-11e7-971e-7f7e404b6799.png)

**Comment by wuchangming** [comment]
@caiyawen ,其他日志都挺正常，就是有一个mime.lookup  is not a function, 有点奇怪。
你去/usr/local/lib/node_modules 这个目录下把spy-debugger先删掉。
然后，重新安装一遍试试： sudo npm i spy-debugger -g

**Comment by caiyawen** [comment]
@wuchangming  解决了！！！ 按照你的步骤操作了一遍就可以了。我怀疑会不会是因为我之前是用cnpm安装的。。因为之前也遇到过用npm和cnpm安装有不一样结果的情况，所以还是建议以后用npm吧。。总之非常非常感谢🙏

**Comment by wuchangming** [comment]
@caiyawen ,Cool!

**Comment by numens** [comment]
![image](https://user-images.githubusercontent.com/13229304/30581605-533afd36-9d53-11e7-84ba-44d7c37d2882.png)
![image](https://user-images.githubusercontent.com/13229304/30581629-69f1049e-9d53-11e7-85f8-85a12d6e0ad1.png)
你好，我一开始访问是可以的，过了几秒之后就崩掉了。。求解版本是最新的版本。 @wuchangming

**Comment by wuchangming** [comment]
@numens ，是手机访问任何链接都这样？还是特定链接。nodejs版本是多少？

**Comment by numens** [comment]
访问任何连接都是这样，一开始是连接成功的，过一会就断开连接了
node版本8.0.0 @wuchangming

**Comment by wuchangming** [comment]
@numens 我装了个8.0.0貌似也没什么问题。

pc用的是mac还是windows？
手机型号和浏览器是？

**Comment by numens** [comment]
@wuchangming 
电脑是mac，
手机IOS10.3.1,
浏览器：电脑谷歌，手机微信

**Comment by wuchangming** [comment]
@numens ,感觉不应该。。。用npm安装的？还是cnpm
重装下spy-debugger试试呢。。

/usr/local/lib/node_modules 这个目录下把spy-debugger先删掉。
然后，重新安装一遍试试： sudo npm i spy-debugger -g

**Comment by numens** [comment]
还是连接一段时间就会断掉。。很绝望 @wuchangming 
![image](https://user-images.githubusercontent.com/13229304/30673317-ae36fa08-9ea4-11e7-965f-4084a888e61c.png)

**Comment by wuchangming** [comment]
@numens 断掉的时候刷新spy-debugger的页面能否继续使用？

**Comment by numens** [comment]
@wuchangming 断掉之后，手机页面刷新可以用。
连接断了，页面调试console那些不行，抓包功能可以使用

**Comment by wuchangming** [comment]
@numens 直接刷新pc上的调试页面

**Comment by numens** [comment]
@wuchangming 刷新pc上面的页面，页面没问题，调试工具还是不行。

**Comment by numens** [comment]
@wuchangming 我把ss关掉之后就没问题了，23333...
谢谢～

**Comment by wuchangming** [comment]
哈哈，感谢反馈！
看来这个还是要补充下到文档的faq上。。其他人也有遇到类似问题。

**Comment by monw3c** [comment]
今天也调试不了 把shadowsockes和手机ss vpn之类关了就可以了

**Comment by monw3c** [comment]
发现有个问题 在调试器内另存就会报错
`(node:14187) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
`

**Comment by YYYCondi** [comment]
为什么我设置完代理,然后安装证书,手机都不能访问页面了,无论是本地服务器的还是在线的一些页面,我是否应该把之前和PC端设置一致的那些代理改回去啊?

**Comment by wuchangming** [comment]
@YYYCondi 
证书安装成功了？

**Comment by fengyinchao** [comment]
@numens 你说的ss是什么呀，我也遇到类似的问题

**Comment by sangongchi** [comment]
> ss
麻烦问下ss是什么，也是同样的问题
