### ISSUE TITLE
不能在https上使用

### ISSUE THREAD

**Issue by belief-cyf** [wuchangming/spy-debugger#56]
在本地用webpack + node起了一个项目 例如启动在:https://10.0.0.2:9051 上的

手机和电脑处在同一个网段内的 设置完HTTP代理后 手机上就打不开https://10.0.0.2:9051 这个项目了。

我自己电脑的IP 是10.0.0.2   我手动代理的IP填的就是10.0.0.2 端口设置的默认端口，但是手机上就是不能打开这个项目了，取消代理后就可以打开。

访问其他线上的项目是没有问题的，但是开发的时候肯定都是在本地起项目的。 现在本地的项目打不开的话 不好调试啊   不知道是什么原因呢？

**Comment by wuchangming** [comment]
你描述里的地址是**https**的，https://10.0.0.2:9051，换成http呢？ 。你本地用webpack + node项目本身是支持**https**？

**Comment by belief-cyf** [comment]
@wuchangming  我下载证书在本地 去mock的https环境。 因为项目里有些功能需要在https的环境下才能正常运行（录音功能）

**Comment by belief-cyf** [comment]
thank you ~ @wuchangming  试了下   换成http启动项目就可以了。   我想是不是和我本地的https证书不安全有关 
![image](https://user-images.githubusercontent.com/19991842/29961979-ff913858-8f33-11e7-9ed9-6c439f67a30a.png)

**Comment by wuchangming** [comment]
pc上安装下spy-debugger的证书，然后重启试试。

证书路径在pc上的路径：{用户目录}/node-mitmproxy

**Comment by belief-cyf** [comment]
安装了试了    还是不能访问https项目  - -

 跟是不是我本地起的没关系  其他公网上的https项目也不能监听。 

尴尬 - -

**Comment by wuchangming** [comment]
@belief-cyf , 手机是否有安装证书？

**Comment by belief-cyf** [comment]
@wuchangming 安装了的  我现在是在平板上试的   用平板的浏览器访问http的web项目可以监听的到   https的项目捕获不到target

**Comment by wuchangming** [comment]
@belief-cyf ，ipad？iOS的系统？

**Comment by belief-cyf** [comment]
@wuchangming   安卓的  华为平板

**Comment by wuchangming** [comment]
换个启动命令试试 
```
spy-debugger -b false
```

**Comment by belief-cyf** [comment]
@wuchangming 每次刷新https页面就会
![image](https://user-images.githubusercontent.com/19991842/29963149-6f447cba-8f38-11e7-8c72-d8834794cb6e.png)

**Comment by belief-cyf** [comment]
![image](https://user-images.githubusercontent.com/19991842/29963339-050e23b8-8f39-11e7-9c83-e91663cbc469.png)
尴尬~  还是不能访问https

**Comment by wuchangming** [comment]
平板上有没有安装证书？访问http://s.xxx安装

**Comment by belief-cyf** [comment]
我之前用平板自带的浏览器下载了证书  我以为下载下来后就会自动安装上去了 刚刚才发现下载下来的是个html  无法安装。
然后我用平板上的chrome浏览去下载了证书，下载下来后提示我无法安装。我们的平板系统是定制的，可能厂家禁止安装证书，我跟平板开发人员沟通一下看看。
感谢这么耐心的一直在帮我找问题~  thank you

**Comment by wuchangming** [comment]
@belief-cyf ,不客气
安卓安装证书，好像也可以通过导入的方式安装。http://abool.blog.51cto.com/8355508/1429700

**Comment by belief-cyf** [comment]
@wuchangming  安装证书后 可以正常使用了。 thk~
