### ISSUE TITLE
Safari可以调试https 但是微信不行

### ISSUE THREAD

**Issue by sizhijian** [wuchangming/spy-debugger#57]
证书安装成功了 微信的http的可以 Safari的http也可以 https会弹窗询问证书不安全继续访问 也可以  微信的WebView 不弹窗 页面也进不去 iOS 10.3.3 微信版本6.5.15

**Comment by wuchangming** [comment]
iOS的证书需要手动打开，参考：https://github.com/wuchangming/spy-debugger/issues/42

**Comment by sizhijian** [comment]
证书是信任过了的，上面显示已验证。您说的打开是什么意思?

**Comment by wuchangming** [comment]
手机进到这个界面
设置->通用->关于本机->证书信任设置，截图看看

**Comment by sizhijian** [comment]
针对根证书启用完全信任没有打开 。以前只知道去通用-描述文件与设备管理 ，去手动信任 。明天去公司再试一下 ，谢了！🙏🏼
