### ISSUE TITLE
Can not find `CA certificate` or `CA key`. [TypeError: Object [object Object] has no method 'accessSync']

### ISSUE THREAD

**Issue by bluefly1234** [wuchangming/spy-debugger#6]
starting server at http://localhost:52381
CA Cert saved in: /Users/xuzhipeng/node-mitmproxy/node-mitmproxy.ca.crt
CA private key saved in: /Users/xuzhipeng/node-mitmproxy/node-mitmproxy.ca.key.pem
Can not find `CA certificate` or `CA key`. [TypeError: Object [object Object] has no method 'accessSync']

**Comment by wuchangming** [comment]
什么版本的nodejs
