### ISSUE TITLE
如何设置anyproxy转发

### ISSUE THREAD

**Issue by zhengnz** [wuchangming/spy-debugger#65]
你好，请问我要在spy-debugger的基础上让anyproxy能针对域名转发请求，该如何去实现呢？

**Comment by wuchangming** [comment]
内置的anyproxy版本是3.10.4。配置应该按照anyproxy的文档即可。
但你也可以单独启动自己下载安装的anyproxy，通过**设置外部代理**的方式使用。这种方式不仅限于anyproxy，也可以用fiddler、Charles等http代理。

命令如下：
（8888为你pc上启动的http代理端口号）
```
spy-debugger -e http://127.0.0.1:8888
```
