### ISSUE TITLE
安装证书时提示：安装失败，无法读取正式文件

### ISSUE THREAD

**Issue by lck671** [wuchangming/spy-debugger#66]
android 安装证书时提示：安装失败，无法读取正式文件

**Comment by wuchangming** [comment]
现在很多安卓浏览器为了安全考虑，确实禁止直接下载安装证书。你可以换个浏览器看看，或者把证书先导入到手机上再安装。
证书在你PC上的地址：{用户目录}/node-mitmproxy/node-mitmproxy.ca.crt
安装方式参考：http://abool.blog.51cto.com/8355508/1429700

**Comment by lck671** [comment]
非常感谢！
