### ISSUE TITLE
webview内AnyProxy 抓不到https,weinre 无targets

### ISSUE THREAD

**Issue by moki0084** [wuchangming/spy-debugger#7]
如题,使用浏览器打开可以, 
webview内AnyProxy 抓不到https,weinre 无targets

**Comment by wuchangming** [comment]
**能否提供下你的：浏览器类型？手机型号？**

**是否按照下列步骤启动了？**

第一步：手机和PC保持在同一网络下（比如同时连到一个Wi-Fi下）

第二步：命令行输入spy-debugger，按命令行提示用浏览器打开相应地址。

第三步：设置手机的HTTP代理，代理IP地址设置为PC的IP地址，端口为spy-debugger的启动端口(默认端口：9888)。

第四步：安装证书。注：手机必须先设置完代理后再通过(非微信)手机浏览器访问http://spydebugger.com/cert安装证书（手机首次调试需要安装证书，已安装了证书的手机无需重复安装)。

第五步：用手机浏览器访问你要调试的页面即可。

**Comment by moki0084** [comment]
@wuchangming 
步骤是一样, app的http请求还是可以抓取.然而app打开的webview 是不行, 

手机自带浏览器是可以

**Comment by wuchangming** [comment]
启动方式换成 下面这个试试
```
spy-debugger -b false
```

**Comment by moki0084** [comment]
@wuchangming 
weinre 下的targets 要刷新,才在 http://127.0.0.1:55035/ 出现,当webview进行跳链后,会提示Connection lost, reload this page to reconnect.

https那个问题倒是好了

**Comment by wuchangming** [comment]
anyproxy不太稳定，可能是anyproxy崩溃了

**Comment by moki0084** [comment]
找了台有谷歌服务的手机试了一下

www.google.com
{ [Error: socket hang up] code: 'ECONNRESET' }
Cannot read property 'displayName' of undefined
C:\Users\***\AppData\Roaming\nvm\v4.4.4\node_modules\spy-debugger\node_modules\anyproxy\proxy.js:208
                    logUtil.printLog('Caught exception: ' + (err.stack || err), logUtil.T_ERR);
                                                                ^

TypeError: Cannot read property 'displayName' of undefined

**Comment by wuchangming** [comment]
嗯，anyproxy经常会导致整个调试工具崩溃。我找时间优化下。

你也可以把spydebbger结合其他更稳定的代理使用如Charles、Fiddler：
https://github.com/wuchangming/spy-debugger#设置外部代理默认使用anyproxy

**Comment by moki0084** [comment]
spy-debugger -b false -e http://127.0.0.1:8888
这样会生效不? 这样weinre 好像也是有点问题

**Comment by wuchangming** [comment]
什么问题呢？这样就只会启动weinre，不启动anyproxy，然后所有spydebugger的请求都转发到8888端口去

**Comment by moki0084** [comment]
weinre 就复现了抓不了targets

**Comment by jiangxueyang** [comment]
@wuchangming 我按照你上面说的步骤走完了，证书也装好了。现在手机访问页面，没有任何监控呃。注：手机与PC在同一局域网内，且代理到了pc的IP地址，fiddler代理的本地IP。页面是https的。使用命令：spy-debugger -b false启动

**Comment by wuchangming** [comment]
**fiddler代理的本地IP** ？？ 什么意思？
 
@jiangxueyang ,页面抓包的tab下有信息没？

**Comment by jiangxueyang** [comment]
@wuchangming 页面抓包的tab没有任何信息呃。fiddler是用来代理访问链接的，现在代理的是本地环境。而且用了你的软件后，我的PC页面访问页面也不会有监控到。之前用weinre，PC访问页面是可以监控的。

**Comment by wuchangming** [comment]
@jiangxueyang ，spy-debugger默认确实不会走你本地的fiddler。你可以用设置外部代理的模式
spy-debugger -e http://127.0.0.1:(fiddler 启动端口)

**Comment by moki0084** [comment]
目前版本配合 Charles 使用,按照上述步骤, 是可以获取 targets

**Comment by aaawhz** [comment]
为什么只能看到网络请求, 没有target

**Comment by guojingwen** [comment]
我的电脑  mac 10.13.6   node 版本 v10.14.2 
安装了 spy-debugger ,  且手机电脑都安装了证书
https调试
webview内AnyProxy 能看到 https，但是 weinre 无targets

**Comment by guojingwen** [comment]
在同事的电脑试了 是可以调试https, 我这反复琢磨研究，始终找不到原因，为什不能https调试

**Comment by wuchangming** [comment]
@guojingwen ,什么手机？安装完证书是否手动信任？参考：https://github.com/wuchangming/spy-debugger/issues/42

**Comment by guojingwen** [comment]
华为 mate9  系统 9.0.1.179

**Comment by guojingwen** [comment]
我用同事的苹果手机  一样 weinre 无targets， 我觉得跟手机想好无关
我同事spy-debugger版本号 3.7.2，我也更新为 3.7.2 也不行

我只能说一次安装后  是可以用的包括https  ， 一段时间不用又必能用了，，，

**Comment by guojingwen** [comment]
![image](https://user-images.githubusercontent.com/12098305/59667467-63d7b800-91e9-11e9-8c92-dbb6655674a6.png)


![image](https://user-images.githubusercontent.com/12098305/59667566-8a95ee80-91e9-11e9-8639-98badc6de819.png)



![image](https://user-images.githubusercontent.com/12098305/59667587-92559300-91e9-11e9-9464-24ac08502c42.png)

**Comment by guojingwen** [comment]
@wuchangming   在看这个问题吗？

**Comment by wuchangming** [comment]
是某个URL不行？还是所有页面都不行？比如百度呢？

**Comment by guojingwen** [comment]
都不行

**Comment by guojingwen** [comment]
@wuchangming   有没有空周末帮我看看，我两天任意时间都有空，
通过 TeamViewer 操控我的电脑， 我通过 Vysor 把手机屏幕投射到电脑，你同样可以操作我的手机

**Comment by wuchangming** [comment]
@guojingwen ,不一定有空，不过你可以留个联系方式。可以发我邮箱 wuchangmingnice@163.com

**Comment by guojingwen** [comment]
好的 @wuchangming , 给你发邮件了

**Comment by guojingwen** [comment]
使用spy调试，
我的手机android 9 同事的手机 ios12.3 ，我的电脑同事的电脑都是mac 且spy版本一致3.8.3
用我的电脑调试两个手机http均可以，https都不行
用同事的电脑调试两个手机 我的手机android9  https不行

这是我的电脑日志
![image](https://user-images.githubusercontent.com/12098305/60082988-7876fb80-9767-11e9-8080-118be550faa4.png)

**Comment by wuchangming** [comment]
@guojingwen ，可能还是证书的问题。
每台电脑安装spy-debugger的时候，会在该电脑上生成一个唯一的证书。证书是跟着电脑的。

如：
*用我的电脑调试两个手机http均可以，https都不行*
（原因：这两台手机都没有信任你电脑上的证书）
*用同事的电脑调试两个手机 我的手机android9 https不行*
（原因：你的手机没有信任你同事电脑上的证书）

**Comment by guojingwen** [comment]
![image](https://user-images.githubusercontent.com/12098305/60087404-8af53300-976f-11e9-9c05-105e9c6a233c.png)


下载哪一个

**Comment by guojingwen** [comment]
@wuchangming

**Comment by guojingwen** [comment]
![image](https://user-images.githubusercontent.com/12098305/60087780-3f8f5480-9770-11e9-8fbe-5da63869c743.png)

**Comment by guojingwen** [comment]
这个选择哪一个

**Comment by wuchangming** [comment]
第一个
