### ISSUE TITLE
远程调试请教

### ISSUE THREAD

**Issue by Myqilixiang** [wuchangming/spy-debugger#71]
您好，我现在使用vue开发一个面向移动应用开发的ide，ide页面是localhost：8080，开发的目标页面是localhost：8081，通过iframe形式嵌入到8080页面，我想在8080页面添加类似chrome devtools 的调试工具调试iframe里面的8081页面，请问有什么好的实现方式么，希望给件建议什么的 ，万分感谢~

**Comment by wuchangming** [comment]
chrome 本身就支持调试iframe
如下图，可以通过这里选择你要调试的iframe

![image](https://user-images.githubusercontent.com/5039340/35502998-cb5fc4ee-0519-11e8-825b-d622f4a3cb77.png)

**Comment by Myqilixiang** [comment]
是滴，但是依您的经验，有没有直接嵌入一个调试面板。直接指定到iframe中的页面的方式，还有个问题想请教就是weinre不能打印error信息，有什么解决方法么，非常感谢您的回答~

**Comment by wuchangming** [comment]
1. 直接嵌入调试面板？没研究过。我觉得上面说的方式也挺简单了。

2. 你是指spy-debugger 中的weinre ？还是单单weinre？
spy-debugger 中的weinre是能打印error的。当然你也可以用vconsole做替代方案。

**Comment by Myqilixiang** [comment]
单weinre好像不支持console err，能简单说一下您的spy-debugger中是怎么实现error打印的么

**Comment by wuchangming** [comment]
@Myqilixiang ，注入的代码里加了window.onerror

**Comment by Myqilixiang** [comment]
大神再打扰一下，就是您的spy-debuger是面向移动端。需要手机设置代理以及添加证书的，所以您在weinre的基础上做了很多新功能的设计，您的代码我拜读了，佩服之余还有些没看太懂。
我现在需要捕获pc端跨域页面的console，这一点weinre其实是支持的，但是他不能打印错误信息，所以想请教一下如何在weinre源码中注入window.onerror从而实现error捕获。
还有就是您提到的vconsole我看了看他应该也是打印当前页面的console，可能不是很服我的需求。再次感谢您的作答，谢谢~

**Comment by wuchangming** [comment]
weinre 本身是支持console打印的。但默认页面上的错误不会调用console方法。所以，你只需要简单的把错误信息传给console打印即可。

被调试的页面上加入类似这段代码
```
window.onerror = function(message, url, lineNo, columnNo, errorObj){
      console.error(message);
}
```

**Comment by Myqilixiang** [comment]
谢谢我哥的悉心回答，相见恨晚，好使~
