### ISSUE TITLE
页面请求抓包成功，但是通过cordova生成的一个app，无法进行页面调试 

### ISSUE THREAD

**Issue by killdada** [wuchangming/spy-debugger#73]

**Comment by wuchangming** [comment]
@killdada 
试试加个参数
```
spy-debugger -b false
```

**Comment by killdada** [comment]
![Uploading QQ图片20180301182309.png…]()
我记得以前用的时候是可以页面调试的，隔了几个月之后在用这个不知道为啥用不了，随便打开的一个百度页面也是无法页面调试，可以抓包，期间公司电脑网络全面升级过一次。

**Comment by killdada** [comment]
![1](https://user-images.githubusercontent.com/16487810/36839780-f5839f8a-1d7d-11e8-9c2d-6f7bf76f2aff.png)
![2](https://user-images.githubusercontent.com/16487810/36839783-f7108fa2-1d7d-11e8-8031-848d04fcc7ba.png)

**Comment by wuchangming** [comment]
手机是否安装了证书？抓包看到的请求有没什么异常？

**Comment by killdada** [comment]
刚看了下，百度的页面可以进行页面调试，应该是公司网络波动。但app 页面还是无法页面调试。请求都是正常的，app里面展示也是正常，

**Comment by wuchangming** [comment]
因为spy-debugger 的原理是拦截html页面注入js代码。如果app页面不是通过http请求的方式打开，或者html被缓存了导致app没有发出http请求html都可能导致spy-debugger无法拦截到。
