### ISSUE TITLE
为什么这个工具 会让原始请求的头 里面键全部变为小写形式?

### ISSUE THREAD

**Issue by TombarthiteL** [wuchangming/spy-debugger#78]
GET /api/CommApi/GetLogoUrl HTTP/1.1
host : hostsz.manger.17boom.com
proxy-connection : keep-alive
pragma : no-cache
origin : http://agentsz.manger.17boom.com
abp.tenantid : 7
user-agent : Mozilla/5.0 (Linux; Android 8.0.0; MI 6 Build/OPR1.170623.027) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.109 Mobile Safari/537.36
content-type : application/json
accept-language : zh-CN
accept : application/json
cache-control : no-cache
x-requested-with : XMLHttpRequest
.aspnetcore.culture : zh-CN
expires : Sat, 01 Jan 2000 00:00:00 GMT
dnt : 1
referer : http://agentsz.manger.17boom.com/account/login?tenantname=szqp
connection : close
content-length : 0

全部被转换为小写了 

原始头
.AspNetCore.Culture: zh-CN
Abp.TenantId: 7
Accept: application/json
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
DNT: 1
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Host: hostsz.manger.17boom.com
Origin: http://agentsz.manger.17boom.com
Pragma: no-cache
Referer: http://agentsz.manger.17boom.com/account/login?tenantname=szqp
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1
X-Requested-With: XMLHttpRequest

请求的返回值好像也看不到

**Comment by wuchangming** [comment]
@TombarthiteL ，确实是的。我开发这个工具的时候也发现这个问题，好像是用了https://github.com/request/request 的原因（有点久不太确定了）。当时我查了下http协议内容，按定义头的key是不区分大小写的，后面我就没处理了。
