### ISSUE TITLE
启动失败 Error: listen EADDRINUSE :::9888 ，实际上9888端口并未被占用

### ISSUE THREAD

**Issue by nwa2018** [wuchangming/spy-debugger#82]
运行spy-debugger报错信息如下(昨天还能跑的)
警告：启动失败 Error: listen EADDRINUSE :::9888
检查端口9888是否被占用
(node:34674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:34674) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

通过lsof -i:9888 查看到端口并没未被占用

**Comment by wuchangming** [comment]
换个端口试试呢
spy-debugger -p 8888

**Comment by nwa2018** [comment]
换了端口，可以了！
