### ISSUE TITLE
证书没找到

### ISSUE THREAD

**Issue by YYYCondi** [wuchangming/spy-debugger#86]
DELL\AppData\Roaming\npm\node_modules\spy-debugger\node_modules\_node-mitmproxy@3.1.0@node-mitmproxy
这个目录下面并没有证书,小米自带浏览器是不能下载,所以想放上去自己安装的,但是根本找不到;我也试过spy-debugger initCA,只是启动了,但是没有生成证书

**Comment by wuchangming** [comment]
正常证书地址是在：{用户目录}/node-mitmproxy    下面
有报错吗？

**Comment by YYYCondi** [comment]
谢谢,我已经找到了,之前是按照网上的说明找,万分感谢 @wuchangming

**Comment by wuchangming** [comment]
fixed
