### ISSUE TITLE
Nodejs 10.x 版本启动, 收到请求之后anyproxy会异常退出并重启

### ISSUE THREAD

**Issue by 15vTechAdmin** [wuchangming/spy-debugger#89]
```shell
$npx spy-debugger
正在启动代理
本机在当前网络下的IP地址为：192.168.204.54
node-mitmproxy启动端口: 9888
浏览器打开 ---> http://127.0.0.1:63642
anyproxy异常退出，尝试重启
重启成功！请手动刷新浏览器
^C
```

不断的重启

使用 nodejs 8.x 正常

**Comment by wuchangming** [comment]
@15vTechAdmin 
刚mac下好像还挺正常的。
1、一启动就不断重启？
2、是mac还是windows？
3、用的是什么node版本管理器？我用的 https://github.com/tj/n 切换的node版本

<img width="300px" src="https://user-images.githubusercontent.com/5039340/40173869-d6d702ec-5a05-11e8-9d6c-138a1cc98670.png" />

**Comment by 15vTechAdmin** [comment]
@wuchangming 

1. 初始启动正常, 当手机发起请求之后不断重启
2. Mac
3. 版本管理器为 nvm

**Comment by wuchangming** [comment]
@15vTechAdmin ,谢谢反馈，node v10下确实有问题。

**Comment by wuchangming** [comment]
@15vTechAdmin ,最新版本`v3.7.0`已修复 。升级了最新的anyproxy

**Comment by 15vTechAdmin** [comment]
awesome!!!
