### ISSUE TITLE
http://spydebugger.com/cert和二维码的地址都无效了。

### ISSUE THREAD

**Issue by wuxiaolan91** [wuchangming/spy-debugger#9]
http://spydebugger.com/cert和二维码的地址都无效了。

**Comment by wuchangming** [comment]
这个地址是只有通过spy-debugger的代理才能访问到的。直接是不能访问的。
证书的安装地址只是代理做了转发。所以**手机要先设置代理后再安装证书** 。

问题同：https://github.com/wuchangming/spy-debugger/issues/3

**Comment by wuxiaolan91** [comment]
是的，我看过#3，还以为自己按照步骤做了还是有问题，但其实我的问题是因为我代理配置问题了所以一直连不上造成的。。

**Comment by wuxiaolan91** [comment]
你可以close我的iuuse了
