### ISSUE TITLE
 Cannot find module 'AnyProxy'

### ISSUE THREAD

**Issue by zhouxinyong** [wuchangming/spy-debugger#95]
![image](https://user-images.githubusercontent.com/15569753/40713442-85763c6a-6432-11e8-8898-acdd777e8538.png)

代码里面是AnyProxy，是否是写错了？

![image](https://user-images.githubusercontent.com/15569753/40713570-de10d8e4-6432-11e8-81d2-9c01cbe67979.png)

**Comment by wuchangming** [comment]
@zhouxinyong ,感谢反馈，确实是个bug。在大小写敏感的OS上是会有问题。

已在 **V3.7.1**版本修复
