### ISSUE TITLE
mac sudo npm install spy-debugger -g  安装报错

### ISSUE THREAD

**Issue by he4398** [wuchangming/spy-debugger#98]
![image](https://user-images.githubusercontent.com/28663449/41836968-d981762e-788e-11e8-9c6b-03b41a8d06f2.png)

**Comment by he4398** [comment]
清除 npm 缓存后安装成功

**Comment by wuchangming** [comment]
@he4398 ，cool。如果没别的问题我先把该issue关闭了？

**Comment by LeoBaruch** [comment]
![image](https://user-images.githubusercontent.com/25567596/53538789-0fc99a80-3b4a-11e9-97ac-ba375c3ce456.png)

系统：macOS 10.13.6
node: vv8.11.4(通过nvm)控制
安装失败

**Comment by UntilGone** [comment]
我这里也出现了这个情况。    清除缓存、淘宝镜像也木有用。  请问有其他解决方案么

**Comment by wuchangming** [comment]
@LeoBaruch @UntilGone 
我用n或者nvm切换过版本后，也出现过类似问题。后来直接去官网重新下载了node.js安装完后就好了。不知道是不是npm的bug。
